//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyntaxHighlighter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\SDK\\geshi-word-addin\\php\\php.exe")]
        public string PHP_EXE {
            get {
                return ((string)(this["PHP_EXE"]));
            }
            set {
                this["PHP_EXE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\SDK\\geshi-word-addin\\cli.php")]
        public string CLI_SCRIPT {
            get {
                return ((string)(this["CLI_SCRIPT"]));
            }
            set {
                this["CLI_SCRIPT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("php")]
        public string LANGUAGE {
            get {
                return ((string)(this["LANGUAGE"]));
            }
            set {
                this["LANGUAGE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LINE_NUMBERS {
            get {
                return ((bool)(this["LINE_NUMBERS"]));
            }
            set {
                this["LINE_NUMBERS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\SDK\\geshi-word-addin\\geshi\\geshi.php")]
        public string GESHI_SCRIPT {
            get {
                return ((string)(this["GESHI_SCRIPT"]));
            }
            set {
                this["GESHI_SCRIPT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\SDK\\geshi-word-addin\\geshi\\geshi")]
        public string GESHI_LANGUAGES {
            get {
                return ((string)(this["GESHI_LANGUAGES"]));
            }
            set {
                this["GESHI_LANGUAGES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SELECTED_LANGUAGES {
            get {
                return ((string)(this["SELECTED_LANGUAGES"]));
            }
            set {
                this["SELECTED_LANGUAGES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AVAILABLE_LANGUAGES {
            get {
                return ((string)(this["AVAILABLE_LANGUAGES"]));
            }
            set {
                this["AVAILABLE_LANGUAGES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int TAB_WIDTH {
            get {
                return ((int)(this["TAB_WIDTH"]));
            }
            set {
                this["TAB_WIDTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime GESHI_LANGUAGES_LAST_WRITE_DATE_TIME {
            get {
                return ((global::System.DateTime)(this["GESHI_LANGUAGES_LAST_WRITE_DATE_TIME"]));
            }
            set {
                this["GESHI_LANGUAGES_LAST_WRITE_DATE_TIME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("!!!")]
        public string MARKER_EXTRA_HIGHLIGHTED_LINES {
            get {
                return ((string)(this["MARKER_EXTRA_HIGHLIGHTED_LINES"]));
            }
            set {
                this["MARKER_EXTRA_HIGHLIGHTED_LINES"] = value;
            }
        }
    }
}
